language: c++
os: linux
dist: bionic
cache:
  directories:
    - ext/llvm-10.0.0.src/include
    - ext/llvm-10.0.0.src/sta/bin
    - ext/llvm-10.0.0.src/sta/lib
    - ext/llvm-10.0.0.src/sta/include
    - ext/llvm-10.0.0.src/projects
    - ext/lld-10.0.0.src/include

compiler: clang

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libncurses5-dev
    - jq
    - cmake
    - ninja-build

before_script:
  - git submodule update --init
  - mkdir -p ext

script:
  - make STATIC_LLVM=1 test
  - make STATIC_LLVM=1 compare
  - bash make-dist.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - bash upload.sh dist/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
